# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

root_project_path = File.dirname(File.dirname(__FILE__))

flutter_application_path = root_project_path + '/flutter_module/'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'SwiftFlutter' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftFlutter

  install_all_flutter_pods(flutter_application_path)
end
